# Generated by Django 4.2.7 on 2025-12-27 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="attendend",
            new_name="attended",
        ),
        migrations.AddField(
            model_name="expenses",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="goals",
            name="achieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="income",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="income",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="income",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="projects",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("On Hold", "On Hold"),
                ],
                default="Planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("Hackathon", "hackathon"),
                    ("AI", "ai"),
                    ("Blockchain", "blockchain"),
                    ("Cybersecurity", "cybersecurity"),
                    ("Other", "other"),
                ],
                default="Hackathon",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Tracker.incomesource",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="wallet",
            field=models.CharField(
                choices=[
                    ("Binance", "Binance"),
                    ("M-pesa", "M-pesa"),
                    ("TrustWallet", "TrustWallet"),
                    ("Bank", "Bank"),
                    ("Paypal", "Paypal"),
                    ("Other", "Other"),
                ],
                default="Bank",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="what_next",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Tracker.nownext",
            ),
        ),
    ]
