# Generated by Django 4.2.7 on 2025-12-28 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0002_rename_attendend_event_attended_expenses_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyFunds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wallet",
                    models.CharField(
                        choices=[
                            ("Binance", "Binance"),
                            ("M-pesa", "M-pesa"),
                            ("TrustWallet", "TrustWallet"),
                            ("Bank", "Bank"),
                            ("Paypal", "Paypal"),
                            ("Other", "Other"),
                        ],
                        default="Bank",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("by_when", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wallet",
                    models.CharField(
                        choices=[
                            ("Binance", "Binance"),
                            ("M-pesa", "M-pesa"),
                            ("TrustWallet", "TrustWallet"),
                            ("Bank", "Bank"),
                            ("Paypal", "Paypal"),
                            ("Other", "Other"),
                        ],
                        default="Bank",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
