# Generated by Django 4.2.7 on 2026-01-01 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tracker", "0003_emergencyfunds_incomegoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyfunds",
            name="user",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incomegoal",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emergencyfunds",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.CharField(default="BCL", max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="worth",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="goals",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incomegoal",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="incomesource",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incomesource",
            name="worth",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="nownext",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="projects",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
