# Generated by Django 4.2.7 on 2026-01-02 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tracker", "0004_emergencyfunds_user_incomegoal_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pictures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(default="", max_length=100)),
                ("model", models.CharField(default="", max_length=100)),
                ("year", models.IntegerField(default=2024)),
                ("picture", models.ImageField(upload_to="car_pictures/")),
            ],
        ),
        migrations.CreateModel(
            name="DreamCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(default="", max_length=100)),
                ("model", models.CharField(default="", max_length=100)),
                ("horsepower", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=2024)),
                ("price", models.FloatField(default=0)),
                ("bought", models.BooleanField(default=False)),
                ("date_bought", models.DateTimeField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(default="")),
                ("pictures", models.ManyToManyField(blank=True, to="Tracker.pictures")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
