# Generated by Django 4.2.7 on 2026-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0006_expenses_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("PERSONAL", "Personal"),
                    ("INVESTMENT", "Investment"),
                    ("FOOD", "Food"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
