# Generated by Django 4.2.7 on 2026-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0007_alter_expenses_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomesource",
            name="got",
            field=models.BooleanField(default=False),
        ),
    ]
